using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace ArtArea.Models
{
    /*
        PIN: 
            - Id : 
                ObjectID generated by MongoDb for concrete pin

            - Message : 
                Message object that stores publication dat, author,... data for pin

            - File : 
                attached source file id (stringed ObjectId) stored in GridFS

            - Thumbnails : 
                list of ids associated with thumbnail files attached to pin stored in GridFS
    */
    public class Pin
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }
        public Message Message { get; set; }

        [BsonRepresentation(BsonType.ObjectId)]
        public string File { get; set; }
        public IEnumerable<string> Thumbnails { get; set; }

    }
}